### ISSUE TITLE
请问有打包好的程序吗

### ISSUE THREAD

**Issue by yangxiaoge** [walgr/ChannelAndSign#2]
想试下加固效果🙂

**Comment by yangxiaoge** [comment]
![image](https://github.com/user-attachments/assets/69a96fa5-e92e-4a0c-b7d4-52c7697a1dc4)
你好，加固所有的apk都报这个错误，请问是什么原因呢🙏

**Comment by walgr** [comment]
你好，最近我来看下，请问机器的java什么版本。

**Comment by walgr** [comment]
看了下dx工具的源码 
![image](https://github.com/user-attachments/assets/27fe162c-4e24-4b78-90f5-048f25b322ed)
这里设置了java.ext.dirs,请试试其他版本jdk，我这openjdk11是可以的。

**Comment by walgr** [comment]
另外，打包可以在desktop下运行packageReleaseExe进行打包。
